### ISSUE TITLE
rawgit

### ISSUE THREAD

**Issue by brody2consult** [dmitrykurmanov/_hf_#1]
<https://rawgit.com/dmitrykurmanov/hypertree/master/example/index.html> does not seem to show a demo for some reason:(

**Comment by brody2consult** [comment]
No dice on gitcdn.xyz either

**Comment by dmitry-kurmanov** [comment]
@brodybits hello! this is not published project, so I don't do anything to create a demo example. In the example folder there is _parcel_ bundler's stuff like imports. So to run in you need to clone the repo and run "npm start". 
This is just an experiment for now. And it is not ready to use)

**Comment by dmitry-kurmanov** [comment]
@brodybits I've create an example with plunker: http://plnkr.co/edit/LXrlHj0DNeKe86s76sGA?p=preview and updated the README, is it ok for you ?

**Comment by brody2consult** [comment]
Nice, thanks! Add to README.md?

**Comment by dmitry-kurmanov** [comment]
@brodybits yes, thank you too!
